#!/usr/bin/env python3
"""
Wildcards: page sections built locally, with no API call and no tokens spent.

Each wildcard is a function that takes an ISO date string and returns
(title, body_html). It must be deterministic — the same date always produces
the same output — so that an archived page keeps its puzzle forever.

Adding another one (kakuro, nonogram, cryptogram) is a three-step job:

    @wildcard("kakuro")
    def kakuro(date_iso):
        ...
        return "Kakuro", body_html

...then list its key under `wildcards:` in prompts.yaml. Nothing in
generate.py needs to change.
"""

import math
import random
from datetime import datetime

# --------------------------------------------------------------------------
# Registry
# --------------------------------------------------------------------------
REGISTRY = {}


def wildcard(key):
    def deco(fn):
        REGISTRY[key] = fn
        return fn
    return deco


def seeded_rng(date_iso, salt=""):
    """A random generator pinned to the date, so output is reproducible."""
    return random.Random(f"{date_iso}|{salt}")


def pick(date_iso, keys, count=1):
    """Choose `count` wildcard keys for this date, cycling evenly through them."""
    keys = [k for k in keys if k in REGISTRY]
    if not keys or count <= 0:
        return []
    day = datetime.strptime(date_iso, "%Y-%m-%d").timetuple().tm_yday
    start = (day * count) % len(keys)
    return [keys[(start + i) % len(keys)] for i in range(min(count, len(keys)))]


def build(key, date_iso):
    return REGISTRY[key](date_iso)


# ==========================================================================
# SHIKAKU
#
# Partition a grid into rectangles; each holds exactly one number equal to
# its area. Generated by recursive splitting, then verified to have exactly
# one solution — a puzzle with two solutions isn't a puzzle.
# ==========================================================================
ROWS, COLS = 7, 7


def _split(r0, c0, h, w, rng, out):
    """Recursively cut a block into rectangles of a pleasant size."""
    area = h * w
    small_enough = area <= 8
    must_stop = h == 1 and w == 1

    if must_stop or (small_enough and (area <= 3 or rng.random() < 0.5)):
        out.append((r0, c0, h, w))
        return

    ways = []
    if h > 1:
        ways.append("h")
    if w > 1:
        ways.append("v")
    if not ways:
        out.append((r0, c0, h, w))
        return

    for _ in range(6):
        way = rng.choice(ways)
        if way == "h":
            cut = rng.randint(1, h - 1)
            a, b = (r0, c0, cut, w), (r0 + cut, c0, h - cut, w)
        else:
            cut = rng.randint(1, w - 1)
            a, b = (r0, c0, h, cut), (r0, c0 + cut, h, w - cut)
        if a[2] * a[3] >= 2 and b[2] * b[3] >= 2:
            _split(*a, rng, out)
            _split(*b, rng, out)
            return

    out.append((r0, c0, h, w))


def _candidates(r, c, area, clue_cells):
    """Every rectangle of the right area that covers (r,c) and no other clue."""
    out = []
    for h in range(1, ROWS + 1):
        if area % h:
            continue
        w = area // h
        if w > COLS:
            continue
        for top in range(max(0, r - h + 1), min(r, ROWS - h) + 1):
            for left in range(max(0, c - w + 1), min(c, COLS - w) + 1):
                if not (top <= r < top + h and left <= c < left + w):
                    continue
                clues_inside = sum(
                    1 for (cr, cc) in clue_cells
                    if top <= cr < top + h and left <= cc < left + w
                )
                if clues_inside == 1:
                    out.append((top, left, h, w))
    return out


def _count_solutions(clues, limit=2):
    """Exact-cover backtracking. Stops as soon as `limit` solutions are found."""
    clue_cells = [(r, c) for (r, c, _) in clues]
    cands = {
        (r, c): _candidates(r, c, a, clue_cells)
        for (r, c, a) in clues
    }
    # Most-constrained clue first keeps the search small.
    order = sorted(cands, key=lambda k: len(cands[k]))
    grid = [[False] * COLS for _ in range(ROWS)]
    found = [0]
    layout = []

    def place(rect, val):
        top, left, h, w = rect
        for rr in range(top, top + h):
            for cc in range(left, left + w):
                grid[rr][cc] = val

    def fits(rect):
        top, left, h, w = rect
        for rr in range(top, top + h):
            for cc in range(left, left + w):
                if grid[rr][cc]:
                    return False
        return True

    def recurse(i, acc):
        if found[0] >= limit:
            return
        if i == len(order):
            found[0] += 1
            if found[0] == 1:
                layout.extend(acc)
            return
        key = order[i]
        for rect in cands[key]:
            if fits(rect):
                place(rect, True)
                acc.append(rect)
                recurse(i + 1, acc)
                acc.pop()
                place(rect, False)
                if found[0] >= limit:
                    return

    recurse(0, [])
    return found[0], layout


def make_shikaku(date_iso, max_attempts=60):
    """Return (clues, solution_rects). Retries until the puzzle is unique."""
    for attempt in range(max_attempts):
        rng = seeded_rng(date_iso, f"shikaku-{attempt}")
        rects = []
        _split(0, 0, ROWS, COLS, rng, rects)
        if len(rects) < 6:
            continue

        clues = []
        for (top, left, h, w) in rects:
            cells = [(top + i, left + j) for i in range(h) for j in range(w)]
            r, c = rng.choice(cells)
            clues.append((r, c, h * w))

        n, layout = _count_solutions(clues, limit=2)
        if n == 1:
            return clues, layout
    raise RuntimeError(f"no unique shikaku for {date_iso}")


def _grid_svg(clues, solution=None, interactive=False):
    cell, pad = 42, 6
    w = COLS * cell + pad * 2
    h = ROWS * cell + pad * 2
    cls = "pz-board" if interactive else "pz-svg"
    parts = [
        f'<svg viewBox="0 0 {w} {h}" class="{cls}" role="img" '
        f'aria-label="Shikaku grid, {ROWS} by {COLS}">'
    ]
    if interactive:
        parts.append('<g class="pz-shapes"></g>')
    parts.append(
        f'<rect x="{pad}" y="{pad}" width="{COLS*cell}" height="{ROWS*cell}" '
        f'fill="none" stroke="var(--ink)" stroke-width="2"/>'
    )
    for i in range(1, COLS):
        x = pad + i * cell
        parts.append(f'<line x1="{x}" y1="{pad}" x2="{x}" y2="{pad+ROWS*cell}" '
                     f'stroke="var(--hair)" stroke-width="1"/>')
    for i in range(1, ROWS):
        y = pad + i * cell
        parts.append(f'<line x1="{pad}" y1="{y}" x2="{pad+COLS*cell}" y2="{y}" '
                     f'stroke="var(--hair)" stroke-width="1"/>')

    if solution:
        for (top, left, rh, rw) in solution:
            parts.append(
                f'<rect x="{pad+left*cell+2}" y="{pad+top*cell+2}" '
                f'width="{rw*cell-4}" height="{rh*cell-4}" fill="none" '
                f'stroke="var(--accent)" stroke-width="2.5" rx="3"/>'
            )

    for (r, c, a) in clues:
        parts.append(
            f'<text x="{pad+c*cell+cell/2}" y="{pad+r*cell+cell/2}" '
            f'text-anchor="middle" dominant-baseline="central" '
            f'class="pz-num">{a}</text>'
        )
    parts.append("</svg>")
    return "".join(parts)


PZ_CSS = """
<style>
.pz-wrap { --pz-line: var(--hair); margin: 0 0 4px; }
.pz-board { touch-action: none; user-select: none; -webkit-user-select: none;
  display: block; width: 100%; max-width: 360px; height: auto; cursor: crosshair; }
.pz-bar { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; margin: 12px 0 0; }
.pz-btn { appearance: none; cursor: pointer; background: transparent;
  border: 1px solid var(--hair); border-radius: 999px; padding: 6px 13px;
  font-family: "JetBrains Mono", monospace; font-size: 11px; letter-spacing: .1em;
  text-transform: uppercase; color: var(--muted); }
.pz-btn:hover { border-color: var(--accent); color: var(--ink); }
.pz-status { font-family: "JetBrains Mono", monospace; font-size: 12px; color: var(--muted); }
.pz-status.is-done { color: var(--accent); }
</style>
"""


PZ_JS = """
<script>
(function () {
  var box = document.getElementById("%(uid)s");
  if (!box) return;
  var svg = box.querySelector(".pz-board");
  var layer = svg.querySelector(".pz-shapes");
  var status = box.querySelector(".pz-status");
  var KEY = "mp-shikaku-%(date)s";
  var R = %(rows)d, C = %(cols)d, CELL = %(cell)d, PAD = %(pad)d;
  var VW = %(vw)d, VH = %(vh)d;
  var CLUES = %(clues)s;
  var rects = [];
  var drag = null;

  function clueAt(r, c) {
    for (var i = 0; i < CLUES.length; i++)
      if (CLUES[i][0] === r && CLUES[i][1] === c) return CLUES[i][2];
    return 0;
  }
  function cellFrom(ev) {
    var b = svg.getBoundingClientRect();
    var x = (ev.clientX - b.left) / b.width * VW;
    var y = (ev.clientY - b.top) / b.height * VH;
    var c = Math.floor((x - PAD) / CELL), r = Math.floor((y - PAD) / CELL);
    if (r < 0 || c < 0 || r >= R || c >= C) return null;
    return { r: r, c: c };
  }
  function norm(a, b) {
    return { top: Math.min(a.r, b.r), left: Math.min(a.c, b.c),
             h: Math.abs(a.r - b.r) + 1, w: Math.abs(a.c - b.c) + 1 };
  }
  function overlaps(x, list) {
    for (var i = 0; i < list.length; i++) {
      var y = list[i];
      if (x.left < y.left + y.w && y.left < x.left + x.w &&
          x.top < y.top + y.h && y.top < x.top + x.h) return true;
    }
    return false;
  }
  function check(x) {
    var found = 0, val = 0;
    for (var i = 0; i < CLUES.length; i++) {
      var cr = CLUES[i][0], cc = CLUES[i][1];
      if (cr >= x.top && cr < x.top + x.h && cc >= x.left && cc < x.left + x.w) {
        found++; val = CLUES[i][2];
      }
    }
    if (found !== 1) return false;
    return val === x.h * x.w;
  }
  function el(tag, attrs) {
    var n = document.createElementNS("http://www.w3.org/2000/svg", tag);
    for (var k in attrs) n.setAttribute(k, attrs[k]);
    return n;
  }
  function draw() {
    while (layer.firstChild) layer.removeChild(layer.firstChild);
    rects.forEach(function (x) {
      layer.appendChild(el("rect", {
        x: PAD + x.left * CELL + 2, y: PAD + x.top * CELL + 2,
        width: x.w * CELL - 4, height: x.h * CELL - 4,
        rx: 3, fill: "var(--accent)", "fill-opacity": "0.13",
        stroke: "var(--accent)", "stroke-width": "2.5"
      }));
    });
    if (drag) {
      var ok = check(drag) && !overlaps(drag, rects);
      layer.appendChild(el("rect", {
        x: PAD + drag.left * CELL + 2, y: PAD + drag.top * CELL + 2,
        width: drag.w * CELL - 4, height: drag.h * CELL - 4,
        rx: 3, fill: ok ? "var(--accent)" : "var(--ink)",
        "fill-opacity": ok ? "0.18" : "0.07",
        stroke: ok ? "var(--accent)" : "var(--muted)",
        "stroke-width": "2", "stroke-dasharray": ok ? "none" : "5 4"
      }));
    }
    var filled = 0;
    rects.forEach(function (x) { filled += x.h * x.w; });
    if (filled === R * C) {
      status.textContent = "Solved.";
      status.className = "pz-status is-done";
    } else {
      status.textContent = filled + " of " + (R * C) + " squares";
      status.className = "pz-status";
    }
  }
  function save() {
    try { localStorage.setItem(KEY, JSON.stringify(rects)); } catch (e) {}
  }
  function load() {
    try {
      var raw = localStorage.getItem(KEY);
      if (!raw) return;
      var got = JSON.parse(raw);
      if (Object.prototype.toString.call(got) === "[object Array]") {
        got.forEach(function (x) {
          if (check(x) && !overlaps(x, rects)) rects.push(x);
        });
      }
    } catch (e) {}
  }

  svg.addEventListener("pointerdown", function (ev) {
    var cell = cellFrom(ev);
    if (!cell) return;
    ev.preventDefault();
    for (var i = 0; i < rects.length; i++) {
      var x = rects[i];
      if (cell.r >= x.top && cell.r < x.top + x.h &&
          cell.c >= x.left && cell.c < x.left + x.w) {
        rects.splice(i, 1); save(); draw(); return;
      }
    }
    drag = { start: cell, top: cell.r, left: cell.c, h: 1, w: 1 };
    svg.setPointerCapture(ev.pointerId);
    draw();
  });
  svg.addEventListener("pointermove", function (ev) {
    if (!drag) return;
    var cell = cellFrom(ev);
    if (!cell) return;
    ev.preventDefault();
    var n = norm(drag.start, cell);
    drag.top = n.top; drag.left = n.left; drag.h = n.h; drag.w = n.w;
    draw();
  });
  function finish(ev) {
    if (!drag) return;
    var cand = { top: drag.top, left: drag.left, h: drag.h, w: drag.w };
    drag = null;
    if (check(cand) && !overlaps(cand, rects)) { rects.push(cand); save(); }
    draw();
  }
  svg.addEventListener("pointerup", finish);
  svg.addEventListener("pointercancel", function () { drag = null; draw(); });

  box.querySelector(".pz-clear").addEventListener("click", function () {
    rects = []; save(); draw();
  });

  load();
  draw();
})();
</script>
"""


@wildcard("shikaku")
def shikaku(date_iso):
    clues, solution = make_shikaku(date_iso)
    uid = "pz-" + date_iso.replace("-", "")
    cell, pad = 42, 6
    vw = COLS * cell + pad * 2
    vh = ROWS * cell + pad * 2

    js = PZ_JS % {
        "uid": uid, "date": date_iso, "rows": ROWS, "cols": COLS,
        "cell": cell, "pad": pad, "vw": vw, "vh": vh,
        "clues": "[" + ",".join(f"[{r},{c},{a}]" for (r, c, a) in clues) + "]",
    }

    body = (
        PZ_CSS
        + '<p class="pz-rule">Divide the grid into rectangles. Every rectangle '
        'holds exactly one number, and that number is how many squares it '
        'covers. Drag to draw a rectangle; tap one to remove it.</p>'
        + f'<div class="pz-wrap" id="{uid}">'
        + _grid_svg(clues, interactive=True)
        + '<div class="pz-bar">'
        '<button type="button" class="pz-btn pz-clear">Clear</button>'
        '<span class="pz-status">0 of 49 squares</span>'
        "</div>"
        + '<details class="pz-reveal"><summary>Show solution</summary>'
        + _grid_svg(clues, solution)
        + "</details>"
        + "</div>"
        + js
    )
    return "Shikaku", body


# ==========================================================================
# FRETBOARD — scale or mode of the day
# ==========================================================================
NOTES = ["A", "A#", "B", "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#"]
STRINGS = ["E", "B", "G", "D", "A", "E"]      # high to low, standard tuning
FRETS = 12

SCALES = [
    ("Ionian (major)",  [0, 2, 4, 5, 7, 9, 11], "Bright, resolved. The reference point for everything else."),
    ("Dorian",          [0, 2, 3, 5, 7, 9, 10], "Minor with a raised sixth — the hopeful minor."),
    ("Phrygian",        [0, 1, 3, 5, 7, 8, 10], "Flat second gives it the Spanish edge."),
    ("Lydian",          [0, 2, 4, 6, 7, 9, 11], "Major with a sharp fourth. Floating, unresolved."),
    ("Mixolydian",      [0, 2, 4, 5, 7, 9, 10], "Major with a flat seventh — the blues-rock workhorse."),
    ("Aeolian (minor)", [0, 2, 3, 5, 7, 8, 10], "The natural minor scale."),
    ("Locrian",         [0, 1, 3, 5, 6, 8, 10], "Diminished fifth, no stable home. Rare and useful."),
    ("Minor pentatonic",[0, 3, 5, 7, 10],       "Five notes, endless mileage. Box one lives here."),
    ("Major pentatonic",[0, 2, 4, 7, 9],        "Sweeter cousin of the minor shape."),
    ("Blues",           [0, 3, 5, 6, 7, 10],    "Minor pentatonic plus the flat five."),
    ("Harmonic minor",  [0, 2, 3, 5, 7, 8, 11], "Raised seventh over a minor scale — the exotic leap."),
    ("Melodic minor",   [0, 2, 3, 5, 7, 9, 11], "Minor third, major sixth and seventh."),
]

DRILLS = [
    "Play it ascending and descending in one position, then shift up a string set.",
    "Loop the root note on a low string and play the scale against it to hear each interval.",
    "Play it in thirds — root, third, second, fourth, and so on up the neck.",
    "Find every root note on the fretboard first, then fill in the shape around each one.",
    "Play it over a single held chord and stop on a different scale tone each pass.",
]


def _fretboard_svg(root_idx, intervals):
    left, top = 34, 26
    fw, sh = 46, 26
    w = left + FRETS * fw + 26
    h = top + (len(STRINGS) - 1) * sh + 34
    tones = {(root_idx + i) % 12 for i in intervals}

    p = [f'<svg viewBox="0 0 {w} {h}" class="fb-svg" role="img" '
         f'aria-label="Fretboard diagram">']

    for i in range(FRETS + 1):
        x = left + i * fw
        width = 3 if i == 0 else 1
        p.append(f'<line x1="{x}" y1="{top}" x2="{x}" y2="{top+(len(STRINGS)-1)*sh}" '
                 f'stroke="var(--ink)" stroke-width="{width}" opacity="0.55"/>')
    for i in range(len(STRINGS)):
        y = top + i * sh
        p.append(f'<line x1="{left}" y1="{y}" x2="{left+FRETS*fw}" y2="{y}" '
                 f'stroke="var(--muted)" stroke-width="1"/>')
    for f in (3, 5, 7, 9, 12):
        p.append(f'<text x="{left+f*fw-fw/2}" y="{top+(len(STRINGS)-1)*sh+22}" '
                 f'text-anchor="middle" class="fb-mark">{f}</text>')

    for si, sname in enumerate(STRINGS):
        open_idx = NOTES.index(sname)
        y = top + si * sh
        p.append(f'<text x="{left-14}" y="{y}" text-anchor="middle" '
                 f'dominant-baseline="central" class="fb-mark">{sname}</text>')
        for fret in range(FRETS + 1):
            n = (open_idx + fret) % 12
            if n not in tones:
                continue
            x = left + (fret * fw if fret == 0 else fret * fw - fw / 2)
            is_root = n == root_idx
            fill = "var(--accent)" if is_root else "var(--paper)"
            stroke = "var(--accent)" if is_root else "var(--ink)"
            tcls = "fb-dot-root" if is_root else "fb-dot-note"
            p.append(f'<circle cx="{x}" cy="{y}" r="10" fill="{fill}" '
                     f'stroke="{stroke}" stroke-width="1.5"/>')
            p.append(f'<text x="{x}" y="{y}" text-anchor="middle" '
                     f'dominant-baseline="central" class="{tcls}">{NOTES[n]}</text>')
    p.append("</svg>")
    return "".join(p)


@wildcard("music")
def music(date_iso):
    rng = seeded_rng(date_iso, "music")
    root = rng.choice(NOTES)
    name, intervals, blurb = rng.choice(SCALES)
    drill = rng.choice(DRILLS)
    root_idx = NOTES.index(root)
    notes = " · ".join(NOTES[(root_idx + i) % 12] for i in intervals)

    body = (
        f'<p class="wc-lead"><strong>{root} {name}</strong> — {blurb}</p>'
        f'<p class="wc-notes">{notes}</p>'
        + _fretboard_svg(root_idx, intervals)
        + f'<p class="wc-drill"><span class="wc-drill-label">Drill</span> {drill}</p>'
    )
    return "Fretboard", body


# ==========================================================================
# NUMBER OF THE DAY
# ==========================================================================
def _factorize(n):
    out, d, m = [], 2, n
    while d * d <= m:
        while m % d == 0:
            out.append(d)
            m //= d
        d += 1
    if m > 1:
        out.append(m)
    return out


def _facts(n):
    f = []
    if n == 1:
        return ["The multiplicative identity — the only number that is neither "
                "prime nor composite.",
                "A perfect square, a triangular number, and a factorial, all at once.",
                "In binary it's 1; in hex, 1."]

    primes = _factorize(n)
    if len(primes) == 1:
        f.append("It's prime.")
    else:
        grouped, seen = [], {}
        for p in primes:
            seen[p] = seen.get(p, 0) + 1
        for p in sorted(seen):
            grouped.append(f"{p}<sup>{seen[p]}</sup>" if seen[p] > 1 else str(p))
        f.append("Factors as " + " × ".join(grouped) + ".")

    r = math.isqrt(n)
    if r * r == n:
        f.append(f"A perfect square — {r}².")
    t = (math.isqrt(8 * n + 1) - 1) / 2
    if t == int(t):
        f.append(f"A triangular number: the sum of 1 through {int(t)}.")
    if n > 1 and (n & (n - 1)) == 0:
        f.append(f"A power of two — 2<sup>{n.bit_length()-1}</sup>.")

    divisors = [d for d in range(1, n) if n % d == 0]
    s = sum(divisors)
    if s == n:
        f.append("Perfect: its proper divisors sum to itself.")
    elif s > n:
        f.append(f"Abundant — its divisors sum to {s}, more than itself.")
    else:
        f.append(f"Deficient — its divisors sum to {s}.")

    f.append(f"In binary it's {n:b}; in hex, {n:X}.")
    if len(divisors) + 1 > 6:
        f.append(f"It has {len(divisors)+1} divisors in total.")
    return f


@wildcard("numbers")
def numbers(date_iso):
    d = datetime.strptime(date_iso, "%Y-%m-%d")
    n = d.timetuple().tm_yday
    items = "".join(f"<li>{x}</li>" for x in _facts(n))
    body = (
        f'<p class="wc-lead">Day <strong>{n}</strong> of the year.</p>'
        f'<ul class="wc-facts">{items}</ul>'
    )
    return f"Number {n}", body
